#:kivy 1.9.0
# File name: Trends.kv

<Trends>:
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: 0.2, 0.2, 0.2, 1
            Rectangle:
                pos: self.pos
                size: self.size
            Color:
                rgba: 0, 0, 0, 1 
            Line:
                rectangle: (self.x, self.y, self.width, self.height)
                width: 1.5
        Label:
            text: 'Trends'